swagger: "2.0"
info:
  version: "2.0.0"
  title: HW2Better
  description: This is the better HW2 with OAuth!
  contact:
    name: William Daniels
    url: https://github.com/willbdaniels
  license:
    name: MIT
    url: http://opensource.org/licenses/MIT
# during dev, should point to your local machine
host: localhost
# basePath prefixes all resource paths 
basePath: /
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
  - applicaiton/x-www-form-urlencoded
# format of the responses to the client (Accepts)
produces:
  - application/json
x-a127-config: 
  RemoteProxy.key: &apigeeProxyKey CONFIGURED
  RemoteProxy.uri: &apigeeProxyUri CONFIGURED
x-a127-services: 
   oauth2: 
      provider: volos-oauth-apigee
      options: 
        tokenLifetime: 300000
        key: *apigeeProxyKey
        uri: *apigeeProxyUri
        validGrantTypes:
          - client_credentials
          - authorization_code
          - implicit_grant
          - password
        passwordCheck:
          helper: volos
          function: passwordCheck
        tokenPaths: 
          authorize: /authorize
          token: /accesstoken
          invalidate: /invalidate
          refresh: /refresh
paths:
  /put:
    # binds a127 app logic to a route
    x-swagger-router-controller: hw2_better
    x-a127-apply: {} 
    put:
      description: Returns response headers containing information about the request
      # used as the method name of the controller
      operationId: put
      parameters:
        - name: name
          in: query
          description: Sends a defined 'put' request to an area
          required: false
          type: string
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/echoServerResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorModel"
      security:
        - oauth2: []
  /delete:
    # binds a127 app logic to a route
    x-swagger-router-controller: hw2_better
    delete:
      description: Returns response headers containing information about the request
      # used as the method name of the controller
      operationId: delete
      parameters:
        - name: name
          in: query
          description: Sends a defined 'delete' request to an area
          required: false
          type: string
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/echoServerResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorModel"
      security:
        - oauth2: []
  /post:
    # binds a127 app logic to a route
    x-swagger-router-controller: hw2_better
    x-a127-apply: {} 
    post:
      description: Returns response headers containing information about the request
      # used as the method name of the controller
      operationId: post
      parameters:
        - name: name
          in: query
          description: Sends a defined 'post' request to an area
          required: false
          type: string
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/echoServerResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorModel"
      security:
        - oauth2: []
  /get:
    # binds a127 app logic to a route
    x-swagger-router-controller: hw2_better
    get:
      description: Returns response headers containing information about the request
      # used as the method name of the controller
      operationId: get
      parameters:
        - name: name
          in: query
          description: Sends a defined 'get' request to an area
          required: false
          type: string
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/echoServerResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorModel"
# complex objects have schema definitions
definitions:
  echoServerResponse:
    required:
      - message
    properties:
      message:
        type: string
  ErrorModel:
    required:
      - message
    properties:
      message:
        type: string
securityDefinitions:
  oauth2: 
    type: oauth2
    scopes: 
      read: "allow read"
    flow: application
    tokenUrl: ignored
