swagger: "2.0"
info:
  version: "0.0.1"
  title: HW3
# during dev, should point to your local machine
host: localhost
# basePath prefixes all resource paths 
basePath: /
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
x-a127-config:
  UCApp.key: &apigeeProxyKey CONFIGURED
  UCApp.uri: &apigeeProxyUri CONFIGURED
x-a127-services:
  quota:
      provider: volos-quota-memory
      options:
        timeUnit: minute
        interval: 1
        allow: 2
  spikearrest:
      provider: "volos-spikearrest-memory"
      options:
        timeUnit: "minute"
        bufferSize: 10
        allow: 10
  cache:
      provider: volos-cache-memory
      options:
        name: hello-cache
        ttl: 60000
  analytics:
      provider: "volos-analytics-apigee"
      options:
        key: *apigeeProxyKey
        uri: *apigeeProxyUri
        proxy: HW3
        bufferSize: 100
        flushInterval: 10
        batchSize: 10
  basic:
      provider: volos-oauth-apigee
      options:
        key: *apigeeProxyKey
        uri: *apigeeProxyUri
        passwordCheck:
          helper: volos
          function: passwordCheck
paths:
  /hello:
    # binds a127 app logic to a route
    x-swagger-router-controller: hello
    x-a127-apply:
      analytics: {}
      quota:
        key:
          helper: volos
          function: quotaHelper
      spikearrest:
        key:
          helper: volos
          function: clientIp
      cache:
        key:
          helper: volos
          function: cacheKey
    get:
      description: Returns 'Hello' to the caller
      # used as the method name of the controller
      operationId: hello
      security:
        - basic: []
      parameters:
        - name: name
          in: query
          description: The name of the person to whom to say hello
          required: false
          type: string
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/HelloWorldResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
# complex objects have schema definitions
definitions:
  HelloWorldResponse:
    required:
      - message
    properties:
      message:
        type: string
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
securityDefinitions:
      basic:
        type: basic
